### ISSUE TITLE
Editing the pattern does not seem to update the pattern setting 0.14.5 in docker

### ISSUE THREAD

**Issue by Petrox** [LavissaWoW/inventree-ipn-generator#2]
Thank you for developing this plugin, seems like plugin for everyone to use.

I tried to change the pattern multiple times.

Then I noticed, that even though the newer value is visible in the settings, if I press the edit value button by the IPN pattern I still get the previous pattern appearing:

![image](https://github.com/LavissaWoW/inventree-ipn-generator/assets/3036509/5da2268a-201d-4240-a39c-52a27c1a3ec5)

Expected: 
 I should see the editor pop up with the SAME value as is visible at the settings table below.

(Note: I was unable to get

DS-001-0001 ... DS-001-9999 kind of pattern with (DS-){3}(-){4} which should work in theory. Maybe the dash - sign is treated as a negative zero number?)

**Comment by LavissaWoW** [comment]
Thank you for the report. 

From what I gather, you're saying the displayed pattern is different between the settings page, and the "edit plugin setting" modal?
The picture seems to show the same value boht places, not different ones?

I'll run some tests and see if I've missed something with dashes. In theory, (DS-001-){4} should've yielded the range DS-001-0001 ... DS-001-9999, so I'll look into that.

**Comment by Petrox** [comment]
Wow, talk about demo effect.   I tried like 8 times to edit that value, then decided it's worth reporting, and just when I wasn't checking anymore (just snapped the pic) it started to behave. 

But back to the issue: yet, the Edit Plugin Setting modal had a different (older) value in the inputbox than what was visible at the Settings table "IPN pattern" row.   

I'm not perfectly sure that it was not a general UI issue (independent from any plugins), but I have reloaded the page, even SHIFT-reload (so any caches should be cleared).

I'll try it again next time and document it better, so I can demonstrate the behaviour better.

**Comment by LavissaWoW** [comment]
I'll deploy the fix to dashes and a couple of other special characters.
In general, InvenTree should handle all settings updates, so I don't think the display issue is directly related to the plugin. I've had a few weird things happen with the Classic UI settings myself, so it wouldn't surprise me if that's the core of the problem there.

I'll close this with the new release.
Feel free to drop a new comment here or raise a new issue if you find something of interest.
