### ISSUE TITLE
Plugin doesn't work in local setup/expected behavior unclear

### ISSUE THREAD

**Issue by wieselukas** [LavissaWoW/inventree-ipn-generator#6]
Hello. First of all thank you very much for developing this Plugin!

Unfortunately I cannot get it running with my local setup. At the same time I don't really know what exact behavior to expect, meaning if the IPN will be visible in the "Create Part" panel already or if the IPN will be filled in upon saving the new part. Either way, with the plugin enabled, pattern set and all other settings activated, no generated IPN appears when creating/saving the part.

**Setup:**
- Inventree 0.14.5 Docker install, Django 4.2.11, Python 3.11.9, API Version 180
- inventree-ipn-generator installed through the inventree web-interface (by pasting "inventree-ipn-generator" as package name into the "Install Plugin" panel)
- Plugin info:
![image](https://github.com/LavissaWoW/inventree-ipn-generator/assets/13906846/2acdc0ac-6986-4e54-8adc-c0c5e995c278)

**Comment by LavissaWoW** [comment]
Have you enabled Event Plugins on the main plugin settings panel?

**Comment by LavissaWoW** [comment]
In terms of behavior, it leverages the Event system of InvenTree, so the IPN will be added after you create or save any given part. It adds an IPN to a part if the IPN field is empty. 
So, the IPN is generated if the field is empty on new parts. And if you delete an IPN on existing parts (with Edit active), then it will get a new IPN from the plugin.

**Comment by wieselukas** [comment]
> Have you enabled Event Plugins on the main plugin settings panel?

Nope, this was exactly the problem. And now looking at your installation instructions I see that I actually overlooked this. Sorry for causing you extra work with my request!
